app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint('main', __name__, template_folder='templates')

from app.main.routes import main_bp

app/main/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from flask_login import login_user, logout_user, login_required
from werkzeug.security import check_password_hash
from app.models import Participants
from flask import Blueprint
from app.main import main_bp

main_bp = Blueprint('main', __name__, template_folder='templates')

@main_bp.route('/')
def index():
    return render_template('main/index.html')

@main_bp.route('/about')
def about():
    return render_template('main/about.html')


@main_bp.route('/profile')
@login_required
def profile():
    return render_template('main/profile.html', name=current_user.first_name)

@main_bp.route('/database')
@login_required
def database():
    return render_template('main/database.html', user=current_user)

app/main/templates/main/about.html
{% extends "main/base.html" %}

{% block content %}

    <!-- Przyciski przekierowujące do grupy na Facebooku -->
    <a href="https://www.facebook.com/groups/717017268691625" class="btn">Our Facebook Group</a>
    <a href="https://www.facebook.com/profile.php?id=100091677889496" class="btn">Our Facebook Funpage</a>
    <a href="https://www.fort.torun.pl/127/forty-biehlera-dzieje-i-wspolczesne-uzytkowanie" class="btn">First International Conference, Toruń 2018 Poland</a>
    <a href="https://www.fort.torun.pl/141/forty-biehlera-historia-i-wspolczesne-uzytkowanie-kaliningrad-baltijsk-22-27-marca-20" class="btn">Second International Conference, Kaliningrad/Baltijsk 2019 Russia</a>
    <a href="https://www.fort.torun.pl/154/trzecia-miedzynarodowa-konferencja-forty-biehlera-historia-i-wspolczesne-uzytkowanie-" class="btn">Third International Conference, Ulm/Ingolstadt 2022 Germany</a>
    <a href="https://www.stadtanzeiger-ortenau.de/kehl-stadt/c-lokales/einzigartige-militaergeschichte-erleben-biehler-forts_a86967" class="btn">Fourth International Conference, Strasbourg/Kehl 2023 France/Germany</a>
    <a href="https://example.com" class="btn">Fifth International Conference, Poznań 2024 Poland</a>

    <div class="page-content">
        <h2>About Us</h2>
        <h3>We look forward to seeing each other soon at Fortress Cologne in Germany from April 8 to 13, 2025.</h3>
        <p>Welcome to Biehler Forts, where we are dedicated to preserving and promoting the historical significance of fortresses through collaboration, research, and education.</p>

        <p>Our task is to organise the events dedicated to the history and architectural issues of the 19th century forts, built to the design of General Alexis von Biehler.</p>

        <p>Our project also pays attention to earlier and later building eras, as they influenced the appearance of the outer rings of Biehler's forts or the improvement of already
            existing structures after 1870. These self-sufficient fortifications from the last quarter of the 19th century still have important historical and architectural
            significance for modern fortress research.</p>

        <p>Our conferences have already resulted, among other things, in the establishment of cross-border cooperation and an international fortress fraternity. So far, the conferences
            have been attended by more than 100 participants, who stay in touch with each other, are keen to offer advice, share experience, materials and undertake new joint initiatives.</p>

        <p>The conference consists of two parts - practical and theoretical.</p>

        <p>During the practical part, participants visit sites, including those that are inaccessible on a daily basis.
            This provides a basis for comparative studies of the architectural details of the forts, their use and history. Such studies result, for example, in solutions to restoration
            problems. Particularly important for all participants in the project is also the search for possibilities of contemporary use of fort works, once designed for strictly military
            purposes and very often difficult to maintain.</p>

        <p>During the theoretical part, experts in the field of defence architecture will deliver papers on the history, architecture and uses of ancient military buildings.</p>

        <a href="{{ url_for('main.index') }}" class="btn">Back to Main Menu</a>
    </div>

{% endblock %}

app/main/templates/main/base.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
{% with messages = get_flashed_messages(True) %}
    {% for category, message in messages %}
            <div>
              {{ message }}
            </div>
    {% endfor %}
{% endwith %}
    <header>
        <h1>Biehler-Forts: History and Contemporary Use</h1>
        <img src="{{ url_for('static', filename='logo_biehler_przezr.png') }}" alt="Biehler Forts Logo" class="logo" width="600">
         <nav>
        <a href="{{ url_for('main.index') }}" class="btn">Home</a>
        <a href="{{ url_for('main.about') }}" class="btn">About Us</a>
        <a href="{{ url_for('auth.signup') }}" class="btn">Sign up</a>
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('main.profile') }}" class="btn">Profile</a>
        <a href="{{ url_for('auth.logout') }}" class="btn">Logout</a>
        {% else %}
        <a href="{{ url_for('auth.login') }}" class="btn">Login</a>
        <a href="{{ url_for('auth.reset_password_request') }}" class="btn">Reset Password</a>
        {% endif %}
        </nav>
    </header>
    <main>
 {% block content %} {% endblock %}



    <!--<footer>
        <p>&copy; 2024 Biehler Forts Project</p>
    </footer>
</body>
</html>

app/main/templates/main/database.html
{% extends "main/base.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Participants</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <h1>Participants</h1>

    <!-- Debugging: Sprawdzenie danych użytkownika -->
    <p>Current User: {{ user.email }}</p>
    <p>Is Coordinator: {{ user.coordinator }}</p>

    <table border="1">
        <tr>
            <th>ID</th>
            <th>Fortress</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Additional Info</th>
        </tr>
        {% for participant in participants %}
        <tr>
            <td>{{ participant.id }}</td>
            <td>{{ participant.fortress }}</td>
            <td>{{ participant.first_name }}</td>
            <td>{{ participant.last_name }}</td>
            <td>{{ participant.email }}</td>
            <td>{{ participant.phone_number }}</td>
            <td>{{ participant.additional_info }}</td>
        </tr>
        {% endfor %}
    </table>

    {% if user.coordinator %}
    <h2>Add Participant</h2>
    <form action="{{ url_for('auth.add_user_as_coordinator') }}" method="POST">

        <label for="fortress">Fortress:</label>
        <input type="text" name="fortress" required>

        <label for="email">Email:</label>
        <input type="email" name="email" required>

        <label for="first_name">First Name:</label>
        <input type="text" name="first_name" required>

        <label for="last_name">Last Name:</label>
        <input type="text" name="last_name" required>

        <button type="submit">Add Participant</button>
    </form>

    <h2>Send message to all participants</h2>
    <form action="{{ url_for('auth.send_message_to_all_participants') }}" method="POST">

        <label for="text">Message:</label>
        <textarea name="text" required></textarea>
        <button type="submit">Send message</button>
    </form>

</body>
</html>
    {% endif %}
</body>
</html>
{% endblock %}

app/main/templates/main/index.html
{% extends "main/base.html" %}
{% block content %}

<script>
function translatePage(language) {
    fetch(`/translate?lang=${language}`)
    .then(response => response.json())
    .then(data => {
        document.body.innerHTML = data.translated_content;
    });
}
</script>


<div class="info">
    <p>Welcome to Biehler Forts, where history meets modern engagement.</p>
    <a href = "mailto:biehler.forts@gmail.com?subject=Email%20Subject&body=Email%20Body%20Text">Email to Biehler Forts Project</a>
</div>
{% endblock %}

app/main/templates/main/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profil</title>
  <h1 class="title">
  Welcome, {{ name }}!
</h1>
</head>
<body>

</body>
</html>